//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AssetID { get; set; }
        public string Name { get; set; }
        public string Heading { get; set; }
        public string Message { get; set; }
        public string Link { get; set; }
        public string Label { get; set; }
        public string Above { get; set; }
        public int Frequency { get; set; }
        public int Times { get; set; }
        public int Total { get; set; }
        public Nullable<System.DateTime> Last { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
