//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carousel
    {
        public int AssetID { get; set; }
        public string Title { get; set; }
        public string Lead { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Label { get; set; }
        public string Link { get; set; }
        public bool Left { get; set; }
        public int Display { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
