//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistration
    {
        public int AssetID { get; set; }
        public int SportID { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Description { get; set; }
        public string Website { get; set; }
        public System.DateTime Submitted { get; set; }
        public System.DateTime Scheduled { get; set; }
        public bool Deleted { get; set; }
    }
}
