//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        public int id { get; set; }
        public string val { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> deleted { get; set; }
    }
}
