//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public int AssetID { get; set; }
        public int SessionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Night { get; set; }
        public string EZRegister { get; set; }
        public string EZSchedule { get; set; }
        public double Cost { get; set; }
        public int Display { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
