//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int AssetID { get; set; }
        public int SportID { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public bool Hourly { get; set; }
        public string Benefit1 { get; set; }
        public string Benefit2 { get; set; }
        public string Benefit3 { get; set; }
        public string Value { get; set; }
        public int Display { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
