//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDetail
    {
        public int ID { get; set; }
        public int LogID { get; set; }
        public string Field { get; set; }
        public string Was { get; set; }
        public string Now { get; set; }
    }
}
