//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seeking
    {
        public int ID { get; set; }
        public int PlayerID { get; set; }
        public string Team { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Filled { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public bool Deleted { get; set; }
    }
}
