//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int AssetID { get; set; }
        public int SportID { get; set; }
        public string Name { get; set; }
        public System.DateTime Deadline { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
