//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int AssetID { get; set; }
        public string Alert { get; set; }
        public Nullable<System.DateTime> AlertStart { get; set; }
        public Nullable<System.DateTime> AlertEnd { get; set; }
        public string EmailFrom { get; set; }
        public string EventTo { get; set; }
        public string EventCc { get; set; }
        public string EventBcc { get; set; }
        public string ContactTo { get; set; }
        public string ContactCc { get; set; }
        public string ContactBcc { get; set; }
        public Nullable<int> LeagueError { get; set; }
        public Nullable<int> LeagueWarning { get; set; }
        public Nullable<int> Lesson { get; set; }
        public Nullable<int> Event { get; set; }
        public Nullable<int> Players { get; set; }
        public Nullable<int> Teams { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool Deleted { get; set; }
    }
}
