//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int AssetID { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Web { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public bool Featured { get; set; }
        public string Advertisement { get; set; }
        public string Link { get; set; }
        public int Total { get; set; }
        public Nullable<System.DateTime> Last { get; set; }
        public int Display { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
