//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionMember
    {
        public int ID { get; set; }
        public int SubscriptionID { get; set; }
        public int TypeID { get; set; }
        public System.DateTime Created { get; set; }
        public bool Deleted { get; set; }
    }
}
