//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int AssetID { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Testimonial1 { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public int Display { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
